### ISSUE TITLE
Baliček nevrací kontrétní chybu, ale pouze error “Not same“

### ISSUE THREAD

**Issue by SerCode** [jirizikes/jest-expect-in-any-order#1]
Kontrolování složených objektů v různém pořadí vrací pouze error “Not same“ a ne konkrétní chybu, což je nepraktické pro debugování.

Bylo by dobré tento package upravit. 

😁

**Comment by SerCode** [comment]
https://github.com/jirizikes/jest-expect-in-any-order/pull/2 <- merge request

**Comment by jirizikes** [comment]
#2 Merged
